// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject3
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// AdminLogIn - Use 'AdminLogInParams' to pass parameters into this method.
        /// </summary>
        public void AdminLogIn()
        {
            #region Variable Declarations
            WinComboBox uIItemComboBox = this.UIMozillaFirefoxWindow.UIPaseknarzędzinawigacToolBar.UIItemComboBox;
            WinList uIItemList = this.UIMozillaFirefoxWindow.UIItemGroup.UIItemList;
            WinEdit uILoginEdit = this.UIMozillaFirefoxWindow.UILoginHyperlink.UILoginEdit;
            WinEdit uIUsernameEdit = this.UIMozillaFirefoxWindow.UIItemDocument.UIUsernameEdit;
            WinEdit uIPasswordEdit = this.UIMozillaFirefoxWindow.UIItemDocument.UIPasswordEdit;
            WinButton uILoginButton = this.UIMozillaFirefoxWindow.UIItemDocument.UILoginButton;
            #endregion

            // Launch '%ProgramW6432%\Mozilla Firefox\firefox.exe'
            ApplicationUnderTest firefoxApplication = ApplicationUnderTest.Launch(this.AdminLogInParams.ExePath, this.AdminLogInParams.AlternateExePath);

            // Select 'local heroes' in combo box
            uIItemComboBox.EditableItem = this.AdminLogInParams.UIItemComboBoxEditableItem;

            // Select '' in list box
            uIItemList.SelectedItemsAsString = this.AdminLogInParams.UIItemListSelectedItemsAsString;

            // Click 'Log in' text box
            Mouse.Click(uILoginEdit, new Point(14, 13));

            // Type 'Admin' in 'User name' text box
            uIUsernameEdit.Text = this.AdminLogInParams.UIUsernameEditText;

            // Type '{Tab}' in 'User name' text box
            Keyboard.SendKeys(uIUsernameEdit, this.AdminLogInParams.UIUsernameEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.AdminLogInParams.UIPasswordEditSendKeys, true);

            // Click 'Log in' button
            Mouse.Click(uILoginButton, new Point(39, 9));
        }
        
        /// <summary>
        /// AdminLogIn1 - Use 'AdminLogIn1Params' to pass parameters into this method.
        /// </summary>
        public void AdminLogIn1()
        {
            #region Variable Declarations
            WinButton uIFirefoxButton = this.UIAAAsAreBecomingABSURWindow.UIPaseknarzędzinawigacToolBar.UIFirefoxButton;
            WinButton uINoweoknoButton = this.UIItemWindow.UIItemGroup.UINoweoknoButton;
            WinComboBox uIItemComboBox = this.UIMozillaFirefoxWindow.UIPaseknarzędzinawigacToolBar.UIItemComboBox;
            WinEdit uIWprowadźadreslubszukEdit = this.UIMozillaFirefoxWindow.UIItemComboBox.UIWprowadźadreslubszukEdit;
            WinEdit uILoginEdit = this.UIMozillaFirefoxWindow.UILoginHyperlink.UILoginEdit;
            WinEdit uIUsernameEdit = this.UIMozillaFirefoxWindow.UIItemDocument.UIUsernameEdit;
            WinEdit uIPasswordEdit = this.UIMozillaFirefoxWindow.UIItemDocument.UIPasswordEdit;
            #endregion

            // Click 'Firefox' button
            Mouse.Click(uIFirefoxButton, new Point(17, 14));

            // Click 'Nowe okno' button
            Mouse.Click(uINoweoknoButton, new Point(154, 10));

            // Select 'localhost:63418' in combo box
            uIItemComboBox.EditableItem = this.AdminLogIn1Params.UIItemComboBoxEditableItem;

            // Type '{Enter}' in 'Wprowadź adres lub szukaj w Google' text box
            Keyboard.SendKeys(uIWprowadźadreslubszukEdit, this.AdminLogIn1Params.UIWprowadźadreslubszukEditSendKeys, ModifierKeys.None);

            // Click 'Log in' text box
            Mouse.Click(uILoginEdit, new Point(28, 7));

            // Type 'Admin' in 'User name' text box
            uIUsernameEdit.Text = this.AdminLogIn1Params.UIUsernameEditText;

            // Type '{Tab}' in 'User name' text box
            Keyboard.SendKeys(uIUsernameEdit, this.AdminLogIn1Params.UIUsernameEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.AdminLogIn1Params.UIPasswordEditSendKeys, true);
        }
        
        #region Properties
        public virtual AdminLogInParams AdminLogInParams
        {
            get
            {
                if ((this.mAdminLogInParams == null))
                {
                    this.mAdminLogInParams = new AdminLogInParams();
                }
                return this.mAdminLogInParams;
            }
        }
        
        public virtual AdminLogIn1Params AdminLogIn1Params
        {
            get
            {
                if ((this.mAdminLogIn1Params == null))
                {
                    this.mAdminLogIn1Params = new AdminLogIn1Params();
                }
                return this.mAdminLogIn1Params;
            }
        }
        
        public UIMozillaFirefoxWindow UIMozillaFirefoxWindow
        {
            get
            {
                if ((this.mUIMozillaFirefoxWindow == null))
                {
                    this.mUIMozillaFirefoxWindow = new UIMozillaFirefoxWindow();
                }
                return this.mUIMozillaFirefoxWindow;
            }
        }
        
        public UIAAAsAreBecomingABSURWindow UIAAAsAreBecomingABSURWindow
        {
            get
            {
                if ((this.mUIAAAsAreBecomingABSURWindow == null))
                {
                    this.mUIAAAsAreBecomingABSURWindow = new UIAAAsAreBecomingABSURWindow();
                }
                return this.mUIAAAsAreBecomingABSURWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private AdminLogInParams mAdminLogInParams;
        
        private AdminLogIn1Params mAdminLogIn1Params;
        
        private UIMozillaFirefoxWindow mUIMozillaFirefoxWindow;
        
        private UIAAAsAreBecomingABSURWindow mUIAAAsAreBecomingABSURWindow;
        
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AdminLogIn'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class AdminLogInParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%ProgramW6432%\Mozilla Firefox\firefox.exe'
        /// </summary>
        public string ExePath = "C:\\Program Files\\Mozilla Firefox\\firefox.exe";
        
        /// <summary>
        /// Launch '%ProgramW6432%\Mozilla Firefox\firefox.exe'
        /// </summary>
        public string AlternateExePath = "%ProgramW6432%\\Mozilla Firefox\\firefox.exe";
        
        /// <summary>
        /// Select 'local heroes' in combo box
        /// </summary>
        public string UIItemComboBoxEditableItem = "local heroes";
        
        /// <summary>
        /// Select '' in list box
        /// </summary>
        public string UIItemListSelectedItemsAsString = "";
        
        /// <summary>
        /// Type 'Admin' in 'User name' text box
        /// </summary>
        public string UIUsernameEditText = "Admin";
        
        /// <summary>
        /// Type '{Tab}' in 'User name' text box
        /// </summary>
        public string UIUsernameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "8LkfRdwPx81+BvOdXGdCtfAL+Dcv75XlkzI+Vs5lLuLsGcGSWTS25QPs0e5LA4IF";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AdminLogIn1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class AdminLogIn1Params
    {
        
        #region Fields
        /// <summary>
        /// Select 'localhost:63418' in combo box
        /// </summary>
        public string UIItemComboBoxEditableItem = "localhost:63418";
        
        /// <summary>
        /// Type '{Enter}' in 'Wprowadź adres lub szukaj w Google' text box
        /// </summary>
        public string UIWprowadźadreslubszukEditSendKeys = "{Enter}";
        
        /// <summary>
        /// Type 'Admin' in 'User name' text box
        /// </summary>
        public string UIUsernameEditText = "Admin";
        
        /// <summary>
        /// Type '{Tab}' in 'User name' text box
        /// </summary>
        public string UIUsernameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "8LkfRdwPx81+BvOdXGdCtfAL+Dcv75XlkzI+Vs5lLuJ0drRCIKtoD3ofEe41z2UxXDwBXNm9H3w=";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIMozillaFirefoxWindow : WinWindow
    {
        
        public UIMozillaFirefoxWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Mozilla Firefox";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MozillaWindowClass";
            this.WindowTitles.Add("Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public UIPaseknarzędzinawigacToolBar UIPaseknarzędzinawigacToolBar
        {
            get
            {
                if ((this.mUIPaseknarzędzinawigacToolBar == null))
                {
                    this.mUIPaseknarzędzinawigacToolBar = new UIPaseknarzędzinawigacToolBar(this);
                }
                return this.mUIPaseknarzędzinawigacToolBar;
            }
        }
        
        public UIItemGroup UIItemGroup
        {
            get
            {
                if ((this.mUIItemGroup == null))
                {
                    this.mUIItemGroup = new UIItemGroup(this);
                }
                return this.mUIItemGroup;
            }
        }
        
        public UILoginHyperlink UILoginHyperlink
        {
            get
            {
                if ((this.mUILoginHyperlink == null))
                {
                    this.mUILoginHyperlink = new UILoginHyperlink(this);
                }
                return this.mUILoginHyperlink;
            }
        }
        
        public UIItemDocument UIItemDocument
        {
            get
            {
                if ((this.mUIItemDocument == null))
                {
                    this.mUIItemDocument = new UIItemDocument(this);
                }
                return this.mUIItemDocument;
            }
        }
        
        public UIItemComboBox UIItemComboBox
        {
            get
            {
                if ((this.mUIItemComboBox == null))
                {
                    this.mUIItemComboBox = new UIItemComboBox(this);
                }
                return this.mUIItemComboBox;
            }
        }
        #endregion
        
        #region Fields
        private UIPaseknarzędzinawigacToolBar mUIPaseknarzędzinawigacToolBar;
        
        private UIItemGroup mUIItemGroup;
        
        private UILoginHyperlink mUILoginHyperlink;
        
        private UIItemDocument mUIItemDocument;
        
        private UIItemComboBox mUIItemComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIPaseknarzędzinawigacToolBar : WinToolBar
    {
        
        public UIPaseknarzędzinawigacToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Pasek narzędzi nawigacyjnych";
            this.WindowTitles.Add("Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIItemComboBox
        {
            get
            {
                if ((this.mUIItemComboBox == null))
                {
                    this.mUIItemComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIItemComboBox.WindowTitles.Add("Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIItemComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemGroup : WinGroup
    {
        
        public UIItemGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinList UIItemList
        {
            get
            {
                if ((this.mUIItemList == null))
                {
                    this.mUIItemList = new WinList(this);
                    #region Search Criteria
                    this.mUIItemList.WindowTitles.Add("Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemList;
            }
        }
        #endregion
        
        #region Fields
        private WinList mUIItemList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UILoginHyperlink : WinHyperlink
    {
        
        public UILoginHyperlink(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "Log in";
            this.WindowTitles.Add("Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UILoginEdit
        {
            get
            {
                if ((this.mUILoginEdit == null))
                {
                    this.mUILoginEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUILoginEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Log in";
                    this.mUILoginEdit.WindowTitles.Add("Mozilla Firefox");
                    #endregion
                }
                return this.mUILoginEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUILoginEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemDocument : WinControl
    {
        
        public UIItemDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
            this.WindowTitles.Add("Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIUsernameEdit
        {
            get
            {
                if ((this.mUIUsernameEdit == null))
                {
                    this.mUIUsernameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIUsernameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "User name";
                    this.mUIUsernameEdit.WindowTitles.Add("Mozilla Firefox");
                    #endregion
                }
                return this.mUIUsernameEdit;
            }
        }
        
        public WinEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Password";
                    this.mUIPasswordEdit.WindowTitles.Add("Mozilla Firefox");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public WinButton UILoginButton
        {
            get
            {
                if ((this.mUILoginButton == null))
                {
                    this.mUILoginButton = new WinButton(this);
                    #region Search Criteria
                    this.mUILoginButton.SearchProperties[WinButton.PropertyNames.Name] = "Log in";
                    this.mUILoginButton.WindowTitles.Add("Mozilla Firefox");
                    #endregion
                }
                return this.mUILoginButton;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIUsernameEdit;
        
        private WinEdit mUIPasswordEdit;
        
        private WinButton mUILoginButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemComboBox : WinComboBox
    {
        
        public UIItemComboBox(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIWprowadźadreslubszukEdit
        {
            get
            {
                if ((this.mUIWprowadźadreslubszukEdit == null))
                {
                    this.mUIWprowadźadreslubszukEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIWprowadźadreslubszukEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Wprowadź adres lub szukaj w Google";
                    this.mUIWprowadźadreslubszukEdit.WindowTitles.Add("Mozilla Firefox");
                    #endregion
                }
                return this.mUIWprowadźadreslubszukEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIWprowadźadreslubszukEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIAAAsAreBecomingABSURWindow : WinWindow
    {
        
        public UIAAAsAreBecomingABSURWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "AAAs Are Becoming ABSURD: Artificial Value & The Death of Release Dates | DEEP DI" +
                "VE - YouTube - Mozilla Firefox";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MozillaWindowClass";
            this.WindowTitles.Add("AAAs Are Becoming ABSURD: Artificial Value & The Death of Release Dates | DEEP DI" +
                    "VE - YouTube - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public UIPaseknarzędzinawigacToolBar1 UIPaseknarzędzinawigacToolBar
        {
            get
            {
                if ((this.mUIPaseknarzędzinawigacToolBar == null))
                {
                    this.mUIPaseknarzędzinawigacToolBar = new UIPaseknarzędzinawigacToolBar1(this);
                }
                return this.mUIPaseknarzędzinawigacToolBar;
            }
        }
        #endregion
        
        #region Fields
        private UIPaseknarzędzinawigacToolBar1 mUIPaseknarzędzinawigacToolBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIPaseknarzędzinawigacToolBar1 : WinToolBar
    {
        
        public UIPaseknarzędzinawigacToolBar1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Pasek narzędzi nawigacyjnych";
            this.WindowTitles.Add("AAAs Are Becoming ABSURD: Artificial Value & The Death of Release Dates | DEEP DI" +
                    "VE - YouTube - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinButton UIFirefoxButton
        {
            get
            {
                if ((this.mUIFirefoxButton == null))
                {
                    this.mUIFirefoxButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIFirefoxButton.SearchProperties[WinButton.PropertyNames.Name] = "Firefox";
                    this.mUIFirefoxButton.WindowTitles.Add("AAAs Are Becoming ABSURD: Artificial Value & The Death of Release Dates | DEEP DI" +
                            "VE - YouTube - Mozilla Firefox");
                    #endregion
                }
                return this.mUIFirefoxButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIFirefoxButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Pulpit 1";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }
        
        #region Properties
        public UIItemGroup1 UIItemGroup
        {
            get
            {
                if ((this.mUIItemGroup == null))
                {
                    this.mUIItemGroup = new UIItemGroup1(this);
                }
                return this.mUIItemGroup;
            }
        }
        #endregion
        
        #region Fields
        private UIItemGroup1 mUIItemGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemGroup1 : WinGroup
    {
        
        public UIItemGroup1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("AAAs Are Becoming ABSURD: Artificial Value & The Death of Release Dates | DEEP DI" +
                    "VE - YouTube - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinButton UINoweoknoButton
        {
            get
            {
                if ((this.mUINoweoknoButton == null))
                {
                    this.mUINoweoknoButton = new WinButton(this);
                    #region Search Criteria
                    this.mUINoweoknoButton.SearchProperties[WinButton.PropertyNames.Name] = "Nowe okno";
                    #endregion
                }
                return this.mUINoweoknoButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUINoweoknoButton;
        #endregion
    }
}
